GMLCity Importer
amosproj/amos2024ss04-building-information-enhancer pull request #348
Opened 2024-07-02 12:36 UTC by nicolasbandel

Issue#161
Issue#346

2024-07-02 17:34 UTC, Corgam requested changes
Looks good, except two things

2024-07-02 17:34 UTC, Corgam commented on backend/src/BIE.DataPipeline/DbHelper.cs
> +        private const int MaxCount = 1;//900;
Should it be changed?

2024-07-02 17:34 UTC, Corgam commented on backend/src/BIE.DataPipeline/yaml/building_models.yaml
Please follow the new yaml folder structure, so either put these files into `common`, `developement` or `production` subfolders. Did you merge into your branch the latest `sprint-release`?

2024-07-03 10:04 UTC, nicolasbandel commented on backend/src/BIE.DataPipeline/DbHelper.cs
> +        private const int MaxCount = 1;//900;
No you are right I have reverted it

2024-07-03 10:06 UTC, nicolasbandel commented on backend/src/BIE.DataPipeline/yaml/building_models.yaml
I moved the filles in the folders.

2024-07-03 10:16 UTC, Corgam approved these changes
Looks good, thanks for fixing the comments!

2024-07-03 10:16 UTC, merged